project_id = "ioaalvvkcovbbfxoscxf"

[functions.ingest]
verify_jwt = false

[functions.publish]
verify_jwt = false

[functions.images-refresh]
verify_jwt = false

[functions.hot-auto]
verify_jwt = false

[functions.hot-override]
verify_jwt = false

[functions.create-development]
verify_jwt = false

[functions.dev-upsert]
verify_jwt = false

[functions.images-upload]
verify_jwt = false

[functions.bulk-dev-import]
verify_jwt = false

[functions.dedupe-developments]
verify_jwt = false

[functions.enrich-development]
verify_jwt = false

[functions.compute-area-metrics]
verify_jwt = false

[functions.fetch-crime-data]
verify_jwt = false

[functions.fetch-growth-data]
verify_jwt = false

[functions.fetch-air-quality-data]
verify_jwt = false

[functions.fetch-schools-data]
verify_jwt = false

[functions.fetch-yield-data]
verify_jwt = false

[functions.fetch-greenspace-data]
verify_jwt = false

[functions.fetch-area-boundaries]
verify_jwt = false

[functions.fetch-ward-boundaries]
verify_jwt = false

[functions.compute-pragmatic-price]
verify_jwt = false

[functions.map-neighbourhoods]
verify_jwt = false

[functions.fetch-nearby]
verify_jwt = false
