project_id = "ioaalvvkcovbbfxoscxf"

[functions.ingest]
verify_jwt = false

[functions.publish]
verify_jwt = false

[functions.images-refresh]
verify_jwt = false

[functions.hot-auto]
verify_jwt = false

[functions.hot-override]
verify_jwt = false

[functions.create-development]
verify_jwt = false
