-- Create neighbourhoods table
CREATE TABLE public.neighbourhoods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  borough text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create neighbourhood_polygons table
CREATE TABLE public.neighbourhood_polygons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  neighbourhood_id uuid NOT NULL REFERENCES public.neighbourhoods(id) ON DELETE CASCADE,
  area_type text NOT NULL DEFAULT 'Ward',
  polygon_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  union_geometry jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(neighbourhood_id)
);

-- Enable RLS
ALTER TABLE public.neighbourhoods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.neighbourhood_polygons ENABLE ROW LEVEL SECURITY;

-- Policies for neighbourhoods
CREATE POLICY "Anyone can view neighbourhoods"
  ON public.neighbourhoods FOR SELECT
  USING (true);

CREATE POLICY "Admins can manage neighbourhoods"
  ON public.neighbourhoods FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role));

-- Policies for neighbourhood_polygons
CREATE POLICY "Anyone can view neighbourhood polygons"
  ON public.neighbourhood_polygons FOR SELECT
  USING (true);

CREATE POLICY "Admins can manage neighbourhood polygons"
  ON public.neighbourhood_polygons FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role));

-- Create index on slug for fast lookups
CREATE INDEX idx_neighbourhoods_slug ON public.neighbourhoods(slug);
CREATE INDEX idx_neighbourhoods_borough ON public.neighbourhoods(borough);
CREATE INDEX idx_neighbourhood_polygons_neighbourhood_id ON public.neighbourhood_polygons(neighbourhood_id);

-- Seed neighbourhoods data
INSERT INTO public.neighbourhoods (borough, name, slug) VALUES
('Barking and Dagenham', 'Barking', 'barking'),
('Barking and Dagenham', 'Dagenham', 'dagenham'),
('Barking and Dagenham', 'Becontree', 'becontree'),
('Barking and Dagenham', 'Becontree Heath', 'becontree-heath'),
('Barking and Dagenham', 'Chadwell Heath (LBBD)', 'chadwell-heath-lbbd'),
('Barking and Dagenham', 'Marks Gate', 'marks-gate'),
('Barking and Dagenham', 'Creekmouth', 'creekmouth'),
('Barking and Dagenham', 'Thames View', 'thames-view'),
('Barking and Dagenham', 'Upney', 'upney'),
('Barking and Dagenham', 'Rush Green (LBBD)', 'rush-green-lbbd'),
('Barnet', 'High Barnet', 'high-barnet'),
('Barnet', 'Whetstone', 'whetstone'),
('Barnet', 'Totteridge', 'totteridge'),
('Barnet', 'Finchley Central', 'finchley-central'),
('Barnet', 'East Finchley', 'east-finchley'),
('Barnet', 'West Finchley', 'west-finchley'),
('Barnet', 'Hendon', 'hendon'),
('Barnet', 'Colindale', 'colindale'),
('Barnet', 'Mill Hill', 'mill-hill'),
('Barnet', 'Burnt Oak', 'burnt-oak'),
('Barnet', 'Golders Green', 'golders-green'),
('Barnet', 'Temple Fortune', 'temple-fortune'),
('Barnet', 'Edgware (Barnet)', 'edgware-barnet'),
('Barnet', 'Cricklewood (Barnet)', 'cricklewood-barnet'),
('Bexley', 'Bexleyheath', 'bexleyheath'),
('Bexley', 'Welling', 'welling'),
('Bexley', 'Sidcup', 'sidcup'),
('Bexley', 'Erith', 'erith'),
('Bexley', 'Belvedere', 'belvedere'),
('Bexley', 'Crayford', 'crayford'),
('Bexley', 'Barnehurst', 'barnehurst'),
('Bexley', 'Blackfen', 'blackfen'),
('Bexley', 'Albany Park', 'albany-park'),
('Bexley', 'Thamesmead (Bexley)', 'thamesmead-bexley'),
('Brent', 'Wembley', 'wembley'),
('Brent', 'Wembley Park', 'wembley-park'),
('Brent', 'Alperton', 'alperton'),
('Brent', 'Sudbury', 'sudbury'),
('Brent', 'Preston', 'preston'),
('Brent', 'Kingsbury', 'kingsbury'),
('Brent', 'Neasden', 'neasden'),
('Brent', 'Dollis Hill', 'dollis-hill'),
('Brent', 'Stonebridge', 'stonebridge'),
('Brent', 'Kilburn (Brent)', 'kilburn-brent'),
('Brent', 'Queen''s Park (Brent)', 'queens-park-brent'),
('Brent', 'Kensal Green (Brent)', 'kensal-green-brent'),
('Bromley', 'Bromley', 'bromley'),
('Bromley', 'Beckenham', 'beckenham'),
('Bromley', 'Shortlands', 'shortlands'),
('Bromley', 'Hayes (Bromley)', 'hayes-bromley'),
('Bromley', 'West Wickham', 'west-wickham'),
('Bromley', 'Keston', 'keston'),
('Bromley', 'Chislehurst (Bromley)', 'chislehurst-bromley'),
('Bromley', 'Bickley', 'bickley'),
('Bromley', 'Orpington', 'orpington'),
('Bromley', 'Petts Wood', 'petts-wood'),
('Bromley', 'Farnborough (Bromley)', 'farnborough-bromley'),
('Bromley', 'Biggin Hill', 'biggin-hill'),
('Camden', 'Camden Town', 'camden-town'),
('Camden', 'Primrose Hill', 'primrose-hill'),
('Camden', 'Hampstead', 'hampstead'),
('Camden', 'Belsize Park', 'belsize-park'),
('Camden', 'Swiss Cottage', 'swiss-cottage'),
('Camden', 'Gospel Oak', 'gospel-oak'),
('Camden', 'Kentish Town', 'kentish-town'),
('Camden', 'Tufnell Park (Camden)', 'tufnell-park-camden'),
('Camden', 'Chalk Farm', 'chalk-farm'),
('Camden', 'West Hampstead', 'west-hampstead'),
('Camden', 'Bloomsbury (Camden)', 'bloomsbury-camden'),
('Camden', 'Holborn (Camden)', 'holborn-camden'),
('Camden', 'King''s Cross (Camden)', 'kings-cross-camden'),
('Croydon', 'Croydon (Central)', 'croydon-central'),
('Croydon', 'Addiscombe', 'addiscombe'),
('Croydon', 'South Norwood', 'south-norwood'),
('Croydon', 'Thornton Heath', 'thornton-heath'),
('Croydon', 'Norbury (Croydon)', 'norbury-croydon'),
('Croydon', 'Shirley', 'shirley'),
('Croydon', 'Waddon', 'waddon'),
('Croydon', 'Purley', 'purley'),
('Croydon', 'Kenley', 'kenley'),
('Croydon', 'Coulsdon', 'coulsdon'),
('Croydon', 'Sanderstead', 'sanderstead'),
('Croydon', 'New Addington', 'new-addington'),
('Croydon', 'Upper Norwood (Croydon)', 'upper-norwood-croydon'),
('Ealing', 'Ealing Broadway', 'ealing-broadway'),
('Ealing', 'West Ealing', 'west-ealing'),
('Ealing', 'Northfields', 'northfields'),
('Ealing', 'South Ealing', 'south-ealing'),
('Ealing', 'Hanwell', 'hanwell'),
('Ealing', 'Greenford', 'greenford'),
('Ealing', 'Perivale', 'perivale'),
('Ealing', 'Northolt', 'northolt'),
('Ealing', 'Southall', 'southall'),
('Ealing', 'Acton (Ealing)', 'acton-ealing'),
('Ealing', 'Park Royal (Ealing)', 'park-royal-ealing'),
('Enfield', 'Enfield Town', 'enfield-town'),
('Enfield', 'Bush Hill Park', 'bush-hill-park'),
('Enfield', 'Winchmore Hill', 'winchmore-hill'),
('Enfield', 'Palmers Green', 'palmers-green'),
('Enfield', 'Southgate', 'southgate'),
('Enfield', 'Oakwood (Enfield)', 'oakwood-enfield'),
('Enfield', 'Cockfosters (Enfield)', 'cockfosters-enfield'),
('Enfield', 'Edmonton', 'edmonton'),
('Enfield', 'Ponders End', 'ponders-end'),
('Enfield', 'Enfield Lock', 'enfield-lock'),
('Enfield', 'Brimsdown', 'brimsdown'),
('Greenwich', 'Greenwich', 'greenwich'),
('Greenwich', 'North Greenwich', 'north-greenwich'),
('Greenwich', 'Westcombe Park', 'westcombe-park'),
('Greenwich', 'Blackheath (Greenwich)', 'blackheath-greenwich'),
('Greenwich', 'East Greenwich', 'east-greenwich'),
('Greenwich', 'Charlton', 'charlton'),
('Greenwich', 'Woolwich', 'woolwich'),
('Greenwich', 'Plumstead', 'plumstead'),
('Greenwich', 'Shooters Hill', 'shooters-hill'),
('Greenwich', 'Kidbrooke', 'kidbrooke'),
('Greenwich', 'Eltham', 'eltham'),
('Greenwich', 'Thamesmead (Greenwich)', 'thamesmead-greenwich'),
('Greenwich', 'Abbey Wood (Greenwich)', 'abbey-wood-greenwich'),
('Hackney', 'Hackney Central', 'hackney-central'),
('Hackney', 'London Fields', 'london-fields'),
('Hackney', 'Haggerston', 'haggerston'),
('Hackney', 'De Beauvoir Town', 'de-beauvoir-town'),
('Hackney', 'Dalston', 'dalston'),
('Hackney', 'Stoke Newington', 'stoke-newington'),
('Hackney', 'Stamford Hill (Hackney)', 'stamford-hill-hackney'),
('Hackney', 'Upper Clapton', 'upper-clapton'),
('Hackney', 'Lower Clapton', 'lower-clapton'),
('Hackney', 'Homerton', 'homerton'),
('Hackney', 'Hackney Wick', 'hackney-wick'),
('Hackney', 'Shoreditch (Hackney)', 'shoreditch-hackney'),
('Hackney', 'Hoxton', 'hoxton'),
('Hammersmith and Fulham', 'Hammersmith', 'hammersmith'),
('Hammersmith and Fulham', 'Brook Green', 'brook-green'),
('Hammersmith and Fulham', 'Shepherd''s Bush (H&F)', 'shepherds-bush-hf'),
('Hammersmith and Fulham', 'White City (H&F)', 'white-city-hf'),
('Hammersmith and Fulham', 'Fulham', 'fulham'),
('Hammersmith and Fulham', 'Parsons Green', 'parsons-green'),
('Hammersmith and Fulham', 'Sands End', 'sands-end'),
('Hammersmith and Fulham', 'West Kensington (H&F)', 'west-kensington-hf'),
('Hammersmith and Fulham', 'Old Oak (H&F)', 'old-oak-hf'),
('Haringey', 'Highgate (Haringey)', 'highgate-haringey'),
('Haringey', 'Crouch End', 'crouch-end'),
('Haringey', 'Muswell Hill', 'muswell-hill'),
('Haringey', 'Hornsey', 'hornsey'),
('Haringey', 'Harringay', 'harringay'),
('Haringey', 'Tottenham', 'tottenham'),
('Haringey', 'Tottenham Hale', 'tottenham-hale'),
('Haringey', 'Seven Sisters', 'seven-sisters'),
('Haringey', 'Wood Green', 'wood-green'),
('Haringey', 'Bounds Green (Haringey)', 'bounds-green-haringey'),
('Haringey', 'Stroud Green (Haringey)', 'stroud-green-haringey'),
('Harrow', 'Harrow', 'harrow'),
('Harrow', 'Harrow-on-the-Hill', 'harrow-on-the-hill'),
('Harrow', 'West Harrow', 'west-harrow'),
('Harrow', 'South Harrow', 'south-harrow'),
('Harrow', 'Harrow Weald', 'harrow-weald'),
('Harrow', 'Wealdstone', 'wealdstone'),
('Harrow', 'Kenton (Harrow)', 'kenton-harrow'),
('Harrow', 'Rayners Lane', 'rayners-lane'),
('Harrow', 'North Harrow', 'north-harrow'),
('Harrow', 'Pinner (Harrow)', 'pinner-harrow'),
('Harrow', 'Stanmore (Harrow)', 'stanmore-harrow'),
('Havering', 'Romford', 'romford'),
('Havering', 'Gidea Park', 'gidea-park'),
('Havering', 'Emerson Park', 'emerson-park'),
('Havering', 'Hornchurch', 'hornchurch'),
('Havering', 'Elm Park', 'elm-park'),
('Havering', 'Upminster', 'upminster'),
('Havering', 'Cranham', 'cranham'),
('Havering', 'Rainham', 'rainham'),
('Havering', 'Harold Hill', 'harold-hill'),
('Havering', 'Harold Wood', 'harold-wood'),
('Havering', 'Collier Row', 'collier-row'),
('Hillingdon', 'Uxbridge', 'uxbridge'),
('Hillingdon', 'Cowley', 'cowley'),
('Hillingdon', 'Hillingdon', 'hillingdon'),
('Hillingdon', 'Hayes', 'hayes'),
('Hillingdon', 'Yeading', 'yeading'),
('Hillingdon', 'West Drayton', 'west-drayton'),
('Hillingdon', 'Yiewsley', 'yiewsley'),
('Hillingdon', 'Harlington (Hillingdon)', 'harlington-hillingdon'),
('Hillingdon', 'Heathrow Villages', 'heathrow-villages'),
('Hillingdon', 'Ruislip', 'ruislip'),
('Hillingdon', 'Eastcote', 'eastcote'),
('Hillingdon', 'Northwood (Hillingdon)', 'northwood-hillingdon'),
('Hillingdon', 'Ickenham', 'ickenham'),
('Hillingdon', 'Harefield', 'harefield'),
('Hounslow', 'Hounslow', 'hounslow'),
('Hounslow', 'Hounslow West', 'hounslow-west'),
('Hounslow', 'Heston', 'heston'),
('Hounslow', 'Cranford (Hounslow)', 'cranford-hounslow'),
('Hounslow', 'Osterley', 'osterley'),
('Hounslow', 'Isleworth', 'isleworth'),
('Hounslow', 'Syon', 'syon'),
('Hounslow', 'Brentford', 'brentford'),
('Hounslow', 'Chiswick (Hounslow)', 'chiswick-hounslow'),
('Hounslow', 'Gunnersbury (Hounslow)', 'gunnersbury-hounslow'),
('Hounslow', 'Feltham', 'feltham'),
('Hounslow', 'Hanworth', 'hanworth'),
('Islington', 'Angel', 'angel'),
('Islington', 'Islington', 'islington'),
('Islington', 'Highbury', 'highbury'),
('Islington', 'Canonbury', 'canonbury'),
('Islington', 'Barnsbury', 'barnsbury'),
('Islington', 'Holloway', 'holloway'),
('Islington', 'Archway (Islington)', 'archway-islington'),
('Islington', 'Tufnell Park (Islington)', 'tufnell-park-islington'),
('Islington', 'Finsbury Park (Islington)', 'finsbury-park-islington'),
('Islington', 'Clerkenwell (Islington)', 'clerkenwell-islington'),
('Islington', 'Finsbury', 'finsbury'),
('Kensington and Chelsea', 'South Kensington', 'south-kensington'),
('Kensington and Chelsea', 'Chelsea', 'chelsea'),
('Kensington and Chelsea', 'Sloane Square', 'sloane-square'),
('Kensington and Chelsea', 'Brompton', 'brompton'),
('Kensington and Chelsea', 'Earl''s Court', 'earls-court'),
('Kensington and Chelsea', 'Kensington', 'kensington'),
('Kensington and Chelsea', 'Holland Park', 'holland-park'),
('Kensington and Chelsea', 'Notting Hill (K&C)', 'notting-hill-kc'),
('Kensington and Chelsea', 'Ladbroke Grove', 'ladbroke-grove'),
('Kensington and Chelsea', 'North Kensington', 'north-kensington'),
('Kensington and Chelsea', 'World''s End', 'worlds-end'),
('Kensington and Chelsea', 'West Brompton', 'west-brompton'),
('Kingston upon Thames', 'Kingston', 'kingston'),
('Kingston upon Thames', 'Norbiton', 'norbiton'),
('Kingston upon Thames', 'Coombe', 'coombe'),
('Kingston upon Thames', 'Surbiton', 'surbiton'),
('Kingston upon Thames', 'Berrylands', 'berrylands'),
('Kingston upon Thames', 'Tolworth', 'tolworth'),
('Kingston upon Thames', 'Hook', 'hook'),
('Kingston upon Thames', 'Chessington', 'chessington'),
('Kingston upon Thames', 'Malden Rushett', 'malden-rushett'),
('Kingston upon Thames', 'New Malden (Kingston)', 'new-malden-kingston'),
('Lambeth', 'Waterloo (Lambeth)', 'waterloo-lambeth'),
('Lambeth', 'South Bank (Lambeth)', 'south-bank-lambeth'),
('Lambeth', 'Vauxhall', 'vauxhall'),
('Lambeth', 'Kennington (Lambeth)', 'kennington-lambeth'),
('Lambeth', 'Oval', 'oval'),
('Lambeth', 'Stockwell', 'stockwell'),
('Lambeth', 'Brixton', 'brixton'),
('Lambeth', 'Loughborough Junction', 'loughborough-junction'),
('Lambeth', 'Clapham North (Lambeth)', 'clapham-north-lambeth'),
('Lambeth', 'Streatham', 'streatham'),
('Lambeth', 'Gipsy Hill', 'gipsy-hill'),
('Lambeth', 'West Norwood', 'west-norwood'),
('Lambeth', 'Herne Hill (Lambeth)', 'herne-hill-lambeth'),
('Lewisham', 'Lewisham', 'lewisham'),
('Lewisham', 'Blackheath (Lewisham)', 'blackheath-lewisham'),
('Lewisham', 'Hither Green', 'hither-green'),
('Lewisham', 'Lee (Lewisham)', 'lee-lewisham'),
('Lewisham', 'Catford', 'catford'),
('Lewisham', 'Brockley', 'brockley'),
('Lewisham', 'New Cross', 'new-cross'),
('Lewisham', 'Deptford', 'deptford'),
('Lewisham', 'St John''s', 'st-johns'),
('Lewisham', 'Telegraph Hill', 'telegraph-hill'),
('Lewisham', 'Forest Hill', 'forest-hill'),
('Lewisham', 'Honor Oak', 'honor-oak'),
('Lewisham', 'Sydenham', 'sydenham'),
('Lewisham', 'Grove Park', 'grove-park'),
('Merton', 'Wimbledon', 'wimbledon'),
('Merton', 'Wimbledon Village', 'wimbledon-village'),
('Merton', 'South Wimbledon', 'south-wimbledon'),
('Merton', 'Raynes Park', 'raynes-park'),
('Merton', 'Morden', 'morden'),
('Merton', 'Colliers Wood', 'colliers-wood'),
('Merton', 'Mitcham', 'mitcham'),
('Newham', 'Stratford', 'stratford'),
('Newham', 'Maryland', 'maryland'),
('Newham', 'West Ham', 'west-ham'),
('Newham', 'Plaistow', 'plaistow'),
('Newham', 'Upton Park', 'upton-park'),
('Newham', 'Forest Gate', 'forest-gate'),
('Newham', 'East Ham', 'east-ham'),
('Newham', 'Manor Park', 'manor-park'),
('Newham', 'Little Ilford', 'little-ilford'),
('Newham', 'Canning Town', 'canning-town'),
('Newham', 'Custom House', 'custom-house'),
('Newham', 'Royal Docks', 'royal-docks'),
('Newham', 'North Woolwich', 'north-woolwich'),
('Newham', 'Beckton', 'beckton'),
('Newham', 'Silvertown', 'silvertown'),
('Redbridge', 'Ilford', 'ilford'),
('Redbridge', 'Gants Hill', 'gants-hill'),
('Redbridge', 'Cranbrook', 'cranbrook'),
('Redbridge', 'Redbridge', 'redbridge'),
('Redbridge', 'Barkingside', 'barkingside'),
('Redbridge', 'Fairlop', 'fairlop'),
('Redbridge', 'Clayhall', 'clayhall'),
('Redbridge', 'Hainault', 'hainault'),
('Redbridge', 'Newbury Park', 'newbury-park'),
('Redbridge', 'Seven Kings', 'seven-kings'),
('Redbridge', 'Goodmayes', 'goodmayes'),
('Redbridge', 'Chadwell Heath (Redbridge)', 'chadwell-heath-redbridge'),
('Redbridge', 'South Woodford', 'south-woodford'),
('Redbridge', 'Woodford', 'woodford'),
('Redbridge', 'Wanstead (Redbridge)', 'wanstead-redbridge'),
('Richmond upon Thames', 'Richmond', 'richmond'),
('Richmond upon Thames', 'Kew', 'kew'),
('Richmond upon Thames', 'North Sheen', 'north-sheen'),
('Richmond upon Thames', 'East Sheen', 'east-sheen'),
('Richmond upon Thames', 'Mortlake', 'mortlake'),
('Richmond upon Thames', 'Barnes', 'barnes'),
('Richmond upon Thames', 'Castelnau', 'castelnau'),
('Richmond upon Thames', 'Twickenham', 'twickenham'),
('Richmond upon Thames', 'St Margarets', 'st-margarets'),
('Richmond upon Thames', 'Whitton', 'whitton'),
('Richmond upon Thames', 'Teddington', 'teddington'),
('Richmond upon Thames', 'Hampton', 'hampton'),
('Richmond upon Thames', 'Hampton Hill', 'hampton-hill'),
('Southwark', 'London Bridge/Bankside', 'london-bridge-bankside'),
('Southwark', 'Borough', 'borough'),
('Southwark', 'Elephant & Castle', 'elephant-and-castle'),
('Southwark', 'South Bank (Southwark)', 'south-bank-southwark'),
('Southwark', 'Bermondsey', 'bermondsey'),
('Southwark', 'Rotherhithe', 'rotherhithe'),
('Southwark', 'Canada Water', 'canada-water'),
('Southwark', 'Surrey Quays', 'surrey-quays'),
('Southwark', 'Old Kent Road', 'old-kent-road'),
('Southwark', 'Peckham', 'peckham'),
('Southwark', 'Nunhead', 'nunhead'),
('Southwark', 'Camberwell', 'camberwell'),
('Southwark', 'East Dulwich', 'east-dulwich'),
('Southwark', 'West Dulwich', 'west-dulwich'),
('Sutton', 'Sutton', 'sutton'),
('Sutton', 'Belmont', 'belmont'),
('Sutton', 'Cheam', 'cheam'),
('Sutton', 'North Cheam', 'north-cheam'),
('Sutton', 'Worcester Park (Sutton)', 'worcester-park-sutton'),
('Sutton', 'Carshalton', 'carshalton'),
('Sutton', 'Carshalton Beeches', 'carshalton-beeches'),
('Sutton', 'Wallington', 'wallington'),
('Sutton', 'Beddington', 'beddington'),
('Tower Hamlets', 'Canary Wharf', 'canary-wharf'),
('Tower Hamlets', 'Isle of Dogs', 'isle-of-dogs'),
('Tower Hamlets', 'Poplar', 'poplar'),
('Tower Hamlets', 'Blackwall', 'blackwall'),
('Tower Hamlets', 'Limehouse', 'limehouse'),
('Tower Hamlets', 'Bow', 'bow'),
('Tower Hamlets', 'Mile End', 'mile-end'),
('Tower Hamlets', 'Stepney', 'stepney'),
('Tower Hamlets', 'Whitechapel', 'whitechapel'),
('Tower Hamlets', 'Bethnal Green', 'bethnal-green'),
('Tower Hamlets', 'Spitalfields', 'spitalfields'),
('Tower Hamlets', 'Brick Lane area', 'brick-lane-area'),
('Tower Hamlets', 'Wapping', 'wapping'),
('Waltham Forest', 'Walthamstow', 'walthamstow'),
('Waltham Forest', 'Walthamstow Village', 'walthamstow-village'),
('Waltham Forest', 'Highams Park', 'highams-park'),
('Waltham Forest', 'Chingford', 'chingford'),
('Waltham Forest', 'South Chingford', 'south-chingford'),
('Waltham Forest', 'Leyton', 'leyton'),
('Waltham Forest', 'Leytonstone', 'leytonstone'),
('Waltham Forest', 'Whipps Cross', 'whipps-cross'),
('Wandsworth', 'Battersea', 'battersea'),
('Wandsworth', 'Nine Elms', 'nine-elms'),
('Wandsworth', 'Clapham Junction', 'clapham-junction'),
('Wandsworth', 'Wandsworth Town', 'wandsworth-town'),
('Wandsworth', 'Putney', 'putney'),
('Wandsworth', 'Southfields', 'southfields'),
('Wandsworth', 'East Putney', 'east-putney'),
('Wandsworth', 'Earlsfield', 'earlsfield'),
('Wandsworth', 'Balham (Wandsworth)', 'balham-wandsworth'),
('Wandsworth', 'Tooting', 'tooting'),
('Wandsworth', 'Roehampton', 'roehampton'),
('Westminster', 'Mayfair', 'mayfair'),
('Westminster', 'Marylebone', 'marylebone'),
('Westminster', 'Fitzrovia (Westminster)', 'fitzrovia-westminster'),
('Westminster', 'Soho', 'soho'),
('Westminster', 'St James''s', 'st-jamess'),
('Westminster', 'Belgravia (Westminster)', 'belgravia-westminster'),
('Westminster', 'Pimlico', 'pimlico'),
('Westminster', 'Victoria (Westminster)', 'victoria-westminster'),
('Westminster', 'Westminster', 'westminster'),
('Westminster', 'Bayswater', 'bayswater'),
('Westminster', 'Maida Vale', 'maida-vale'),
('Westminster', 'Little Venice', 'little-venice'),
('Westminster', 'St John''s Wood', 'st-johns-wood'),
('Westminster', 'Paddington', 'paddington'),
('City of London', 'City of London', 'city-of-london'),
('City of London', 'Barbican', 'barbican');