-- Comprehensive London Developments Import
-- Adding extensive portfolio data for all 12 registered developers

-- Berkeley Group Developments
INSERT INTO public.developments (id, name, developer, location, postcode, lat, lng, nearest_tube, nearest_tube_line, distance_to_tube, zone, prices, tenure, completion_date, bedrooms, status, area_overview, transport_score, green_spaces, amenities, images, stations) VALUES

-- Existing Berkeley developments (update with full data)
('berkeley-oval-village', 'Oval Village', 'Berkeley Group', 'Oval, SW9', 'SW9 7QP', 51.4793, -0.1145, 'Oval', 'Northern', '5 min', 'Zone 2', '{"studio": 450000, "1bed": 550000, "2bed": 750000, "3bed": 950000}', 'Leasehold', 'Completed', ARRAY[1,2,3], 'Available', 'Oval Village is a vibrant new neighbourhood in South London, perfectly positioned between Oval and Stockwell stations. This Berkeley Homes development offers contemporary apartment living with excellent transport links into Central London.', '9/10', 'Kennington Park (5 min walk)', ARRAY['gym', 'concierge', 'rooftop_terrace', 'residents_lounge', 'bike_storage', 'landscaped_gardens'], ARRAY['/oval-village-1.png', '/oval-village-2.png', '/oval-village-3.png', '/oval-village-4.png', '/oval-village-5.png', '/oval-village-6.png', '/oval-village-7.png', '/oval-village-8.png'], '[{"station": "Oval", "line": "Northern", "walk_time": 5}, {"station": "Stockwell", "line": "Northern, Victoria", "walk_time": 8}]'),

('berkeley-bow-green', 'Bow Green', 'Berkeley Group', 'Bow, E3', 'E3 2YF', 51.5289, -0.0165, 'Mile End', 'Central, District, Hammersmith & City', '8 min', 'Zone 2', '{"studio": 400000, "1bed": 525000, "2bed": 675000, "3bed": 825000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'Bow Green brings contemporary homes to East London with excellent connections to Canary Wharf and the City. Located in the heart of Bow, this development offers modern living spaces with access to parks and local amenities.', '8/10', 'Victoria Park (10 min walk)', ARRAY['gym', 'concierge', 'bike_storage', 'parcel_room', 'communal_garden'], ARRAY['/placeholder.svg'], '[{"station": "Mile End", "line": "Central, District, Hammersmith & City", "walk_time": 8}, {"station": "Bow Road", "line": "District, Hammersmith & City", "walk_time": 6}]'),

('berkeley-heron-wharf', 'Heron Wharf', 'Berkeley Group', 'Greenwich Peninsula, SE10', 'SE10 0GQ', 51.4992, 0.0065, 'North Greenwich', 'Jubilee', '4 min', 'Zone 2-3', '{"studio": 420000, "1bed": 540000, "2bed": 720000, "3bed": 900000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Heron Wharf is part of the Greenwich Peninsula regeneration, offering riverside living with stunning views across the Thames. Close to the O2 Arena and with direct Jubilee line access, this development combines excellent connectivity with waterside living.', '9/10', 'Greenwich Peninsula Ecology Park (5 min walk)', ARRAY['gym', 'concierge', '24hr_security', 'cinema_room', 'residents_lounge', 'bike_storage', 'river_views'], ARRAY['/placeholder.svg'], '[{"station": "North Greenwich", "line": "Jubilee", "walk_time": 4}]'),

('berkeley-grand-union', 'Grand Union', 'Berkeley Group', 'Alperton, HA0', 'HA0 4PR', 51.5371, -0.2995, 'Alperton', 'Piccadilly', '5 min', 'Zone 4', '{"studio": 340000, "1bed": 425000, "2bed": 550000, "3bed": 675000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Grand Union is a canalside development in Alperton offering modern apartments with excellent transport links. The Piccadilly line provides direct access to the West End and Heathrow Airport.', '7/10', 'Grand Union Canal walks', ARRAY['gym', 'concierge', 'bike_storage', 'landscaped_gardens', 'canalside_terrace'], ARRAY['/placeholder.svg'], '[{"station": "Alperton", "line": "Piccadilly", "walk_time": 5}]'),

('berkeley-goodmans-fields', 'Goodman''s Fields', 'Berkeley Group', 'Aldgate, E1', 'E1 8DA', 51.5144, -0.0706, 'Aldgate', 'Metropolitan, Circle', '3 min', 'Zone 1', '{"studio": 525000, "1bed": 675000, "2bed": 950000, "3bed": 1350000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'Located in the heart of the City, Goodman''s Fields offers luxury apartments with exceptional connectivity. This prime Zone 1 location provides easy access to the financial district and the vibrant areas of Shoreditch and Spitalfields.', '10/10', 'Altab Ali Park (3 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'concierge', '24hr_security', 'cinema_room', 'business_lounge', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Aldgate", "line": "Metropolitan, Circle", "walk_time": 3}, {"station": "Aldgate East", "line": "District, Hammersmith & City", "walk_time": 5}]'),

('berkeley-kidbrooke-village', 'Kidbrooke Village', 'Berkeley Group', 'Kidbrooke, SE3', 'SE3 9LL', 51.4628, 0.0248, 'Kidbrooke', 'Southeastern Railway', '5 min', 'Zone 3', '{"studio": 320000, "1bed": 400000, "2bed": 525000, "3bed": 650000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'Kidbrooke Village is a masterplanned community in South East London, creating a new neighbourhood with parks, shops, and excellent schools. Great connectivity to Canary Wharf and Central London.', '7/10', 'Sutcliffe Park (2 min walk)', ARRAY['gym', 'village_square', 'shops', 'restaurants', 'park', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Kidbrooke", "line": "Southeastern Railway", "walk_time": 5}]'),

('berkeley-royal-arsenal-riverside', 'Royal Arsenal Riverside', 'Berkeley Group', 'Woolwich, SE18', 'SE18 6SP', 51.4903, 0.0696, 'Woolwich Arsenal', 'Elizabeth line, DLR', '6 min', 'Zone 4', '{"studio": 310000, "1bed": 395000, "2bed": 515000, "3bed": 640000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'Royal Arsenal Riverside is a stunning riverside development offering access to the Elizabeth line, bringing Woolwich just 30 minutes from the West End. The heritage setting combines historic architecture with contemporary design.', '9/10', 'Royal Arsenal Gardens (on-site)', ARRAY['gym', 'concierge', 'river_views', 'heritage_square', 'riverside_walk', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Woolwich Arsenal", "line": "Elizabeth line, DLR", "walk_time": 6}, {"station": "Woolwich", "line": "Southeastern Railway", "walk_time": 8}]'),

('berkeley-the-timberyard', 'The Timberyard', 'Berkeley Group', 'Deptford, SE8', 'SE8 4JF', 51.4788, -0.0253, 'Deptford', 'DLR', '4 min', 'Zone 2', '{"studio": 385000, "1bed": 475000, "2bed": 625000, "3bed": 775000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'The Timberyard brings contemporary living to Deptford''s creative quarter. With DLR access to Canary Wharf and excellent local amenities, this development offers vibrant urban living in South East London.', '8/10', 'Deptford Park (8 min walk)', ARRAY['gym', 'concierge', 'rooftop_terrace', 'bike_storage', 'communal_gardens'], ARRAY['/placeholder.svg'], '[{"station": "Deptford", "line": "DLR", "walk_time": 4}]'),

('berkeley-west-end-gate', 'West End Gate', 'Berkeley Group', 'Marylebone, W2', 'W2 1LA', 51.5189, -0.1732, 'Edgware Road', 'Circle, District, Hammersmith & City', '2 min', 'Zone 1', '{"studio": 625000, "1bed": 825000, "2bed": 1250000, "3bed": 1850000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'West End Gate is a landmark development in Marylebone offering luxury apartments with unparalleled access to the West End, Hyde Park, and Paddington. Premium Zone 1 living at its finest.', '10/10', 'Hyde Park (10 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'concierge', '24hr_security', 'cinema_room', 'business_lounge', 'valet_parking', 'sky_gardens'], ARRAY['/placeholder.svg'], '[{"station": "Edgware Road", "line": "Circle, District, Hammersmith & City", "walk_time": 2}, {"station": "Paddington", "line": "Elizabeth line, Circle, District, Bakerloo", "walk_time": 8}]'),

('berkeley-sapphire-gardens', 'Sapphire Gardens', 'Berkeley Group', 'Croydon, CR0', 'CR0 2AJ', 51.3760, -0.0983, 'East Croydon', 'Southern, Thameslink', '7 min', 'Zone 5', '{"studio": 280000, "1bed": 340000, "2bed": 445000, "3bed": 550000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Sapphire Gardens offers modern living in Croydon with excellent rail connections to London Bridge and Victoria. Part of Croydon''s ongoing regeneration with new shops, restaurants, and cultural venues.', '8/10', 'Wandle Park (5 min walk)', ARRAY['gym', 'concierge', 'bike_storage', 'landscaped_gardens', 'residents_lounge'], ARRAY['/placeholder.svg'], '[{"station": "East Croydon", "line": "Southern, Thameslink", "walk_time": 7}]'),

-- Barratt London Developments
('barratt-woodberry-down', 'Woodberry Down', 'Barratt London', 'Finsbury Park, N4', 'N4 2DU', 51.5687, -0.0959, 'Manor House', 'Piccadilly', '8 min', 'Zone 2-3', '{"studio": 375000, "1bed": 465000, "2bed": 615000, "3bed": 765000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Woodberry Down is a major regeneration creating a new community beside reservoirs and parkland. Excellent transport links via the Piccadilly line and close to vibrant Finsbury Park.', '8/10', 'Woodberry Wetlands (on-site)', ARRAY['gym', 'concierge', 'waterside_walks', 'nature_reserve', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Manor House", "line": "Piccadilly", "walk_time": 8}, {"station": "Finsbury Park", "line": "Piccadilly, Victoria", "walk_time": 12}]'),

('barratt-beaufort-park', 'Beaufort Park', 'Barratt London', 'Colindale, NW9', 'NW9 5BL', 51.5954, -0.2496, 'Colindale', 'Northern', '5 min', 'Zone 4', '{"studio": 320000, "1bed": 395000, "2bed": 525000, "3bed": 650000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'Beaufort Park is one of London''s largest residential developments, creating a new community in Colindale with parkland, schools, and excellent Northern line connections.', '8/10', 'RAF Museum Park (3 min walk)', ARRAY['gym', 'concierge', 'swimming_pool', 'tennis_courts', 'village_square', 'park', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Colindale", "line": "Northern", "walk_time": 5}]'),

('barratt-hayes-village', 'Hayes Village', 'Barratt London', 'Hayes, UB3', 'UB3 4DP', 51.5124, -0.4186, 'Hayes & Harlington', 'Elizabeth line, Great Western Railway', '8 min', 'Zone 5', '{"studio": 270000, "1bed": 335000, "2bed": 435000, "3bed": 535000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'Hayes Village benefits from the Elizabeth line, bringing the West End within 30 minutes. This development offers affordable homes with excellent connectivity and local amenities.', '9/10', 'Minet Country Park (10 min walk)', ARRAY['gym', 'concierge', 'village_green', 'play_areas', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Hayes & Harlington", "line": "Elizabeth line, Great Western Railway", "walk_time": 8}]'),

('barratt-ealing-broadway', 'Filmworks Ealing', 'Barratt London', 'Ealing Broadway, W5', 'W5 5FA', 51.5151, -0.3016, 'Ealing Broadway', 'Central, District, Elizabeth line', '2 min', 'Zone 3', '{"studio": 395000, "1bed": 495000, "2bed": 650000, "3bed": 825000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Filmworks is a landmark development in the heart of Ealing Broadway, offering exceptional transport links via the Elizabeth line, Central, and District lines. Perfect for accessing central London.', '10/10', 'Walpole Park (5 min walk)', ARRAY['gym', 'concierge', 'cinema', 'restaurants', 'shops', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Ealing Broadway", "line": "Central, District, Elizabeth line", "walk_time": 2}]'),

('barratt-blackhorse-view', 'Blackhorse View', 'Barratt London', 'Walthamstow, E17', 'E17 6NP', 51.5870, -0.0414, 'Blackhorse Road', 'Victoria', '4 min', 'Zone 3', '{"studio": 340000, "1bed": 425000, "2bed": 560000, "3bed": 690000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Blackhorse View is part of the Blackhorse Lane regeneration, bringing contemporary homes to Walthamstow with Victoria line access to the West End in 25 minutes.', '9/10', 'Walthamstow Wetlands (8 min walk)', ARRAY['gym', 'concierge', 'communal_gardens', 'bike_storage', 'workspace'], ARRAY['/placeholder.svg'], '[{"station": "Blackhorse Road", "line": "Victoria", "walk_time": 4}]'),

-- Ballymore Developments
('ballymore-embassy-gardens', 'Embassy Gardens', 'Ballymore', 'Nine Elms, SW11', 'SW11 7AY', 51.4843, -0.1250, 'Nine Elms', 'Northern', '5 min', 'Zone 1', '{"studio": 525000, "1bed": 675000, "2bed": 950000, "3bed": 1350000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'Embassy Gardens is an iconic development featuring the famous Sky Pool. Located in Nine Elms with Northern line access, this riverside development offers luxury living in Zone 1.', '10/10', 'Vauxhall Park (8 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'sky_pool', 'concierge', '24hr_security', 'cinema_room', 'business_lounge', 'river_views'], ARRAY['/placeholder.svg'], '[{"station": "Nine Elms", "line": "Northern", "walk_time": 5}, {"station": "Vauxhall", "line": "Victoria", "walk_time": 10}]'),

('ballymore-london-city-island', 'London City Island', 'Ballymore', 'Leamouth, E14', 'E14 0JY', 51.5078, -0.0088, 'Canning Town', 'Jubilee, Elizabeth line, DLR', '10 min', 'Zone 2-3', '{"studio": 410000, "1bed": 525000, "2bed": 695000, "3bed": 875000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'London City Island is a unique residential neighbourhood on the River Lea, home to the English National Ballet. Excellent connections to Canary Wharf and the City.', '9/10', 'River Lea waterside walks', ARRAY['gym', 'concierge', 'arts_centre', 'riverside_walks', 'cafe', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Canning Town", "line": "Jubilee, Elizabeth line, DLR", "walk_time": 10}]'),

('ballymore-goodluck-hope', 'Goodluck Hope', 'Ballymore', 'Leamouth, E14', 'E14 0BE', 51.5085, -0.0055, 'Canning Town', 'Jubilee, Elizabeth line, DLR', '12 min', 'Zone 2-3', '{"studio": 395000, "1bed": 505000, "2bed": 670000, "3bed": 840000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'Goodluck Hope continues the transformation of Leamouth Peninsula, offering riverside living close to Canary Wharf with excellent transport connections.', '9/10', 'River Lea Park (on-site)', ARRAY['gym', 'concierge', 'riverside_terrace', 'communal_gardens', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Canning Town", "line": "Jubilee, Elizabeth line, DLR", "walk_time": 12}]'),

-- Bellway London Developments
('bellway-enderby-wharf', 'Enderby Wharf', 'Bellway', 'Greenwich, SE10', 'SE10 0AG', 51.4925, 0.0155, 'North Greenwich', 'Jubilee', '8 min', 'Zone 2-3', '{"studio": 385000, "1bed": 475000, "2bed": 625000, "3bed": 780000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Enderby Wharf is a riverside development in Greenwich offering Thames views and excellent Jubilee line connections. Close to the O2 and Greenwich Peninsula amenities.', '9/10', 'Greenwich Peninsula Ecology Park (5 min walk)', ARRAY['gym', 'concierge', 'riverside_walks', 'bike_storage', 'river_views'], ARRAY['/placeholder.svg'], '[{"station": "North Greenwich", "line": "Jubilee", "walk_time": 8}]'),

('bellway-greenwich-square', 'Greenwich Square', 'Bellway', 'Greenwich, SE10', 'SE10 0EW', 51.4881, 0.0075, 'Maze Hill', 'Southeastern Railway', '5 min', 'Zone 2-3', '{"studio": 370000, "1bed": 460000, "2bed": 605000, "3bed": 750000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'Greenwich Square offers modern living in historic Greenwich with easy access to Greenwich Park, the Royal Observatory, and excellent rail connections to Central London.', '8/10', 'Greenwich Park (5 min walk)', ARRAY['gym', 'concierge', 'communal_gardens', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Maze Hill", "line": "Southeastern Railway", "walk_time": 5}]'),

('bellway-hendon-waterside', 'Hendon Waterside', 'Bellway', 'Hendon, NW9', 'NW9 7EE', 51.5872, -0.2461, 'Hendon', 'Northern', '8 min', 'Zone 3', '{"studio": 340000, "1bed": 425000, "2bed": 560000, "3bed": 695000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'Hendon Waterside is a major regeneration creating a new neighbourhood with waterside living, parkland, and excellent Northern line connections.', '8/10', 'Welsh Harp Reservoir (5 min walk)', ARRAY['gym', 'concierge', 'waterside_walks', 'park', 'bike_storage', 'shops'], ARRAY['/placeholder.svg'], '[{"station": "Hendon", "line": "Northern", "walk_time": 8}]'),

('bellway-meridian-quay', 'Meridian Quay', 'Bellway', 'Greenwich, SE10', 'SE10 0PQ', 51.4910, 0.0025, 'North Greenwich', 'Jubilee', '6 min', 'Zone 2-3', '{"studio": 395000, "1bed": 485000, "2bed": 640000, "3bed": 800000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Meridian Quay offers waterside living in Greenwich Peninsula with easy access to Canary Wharf and Central London via the Jubilee line.', '9/10', 'Greenwich Peninsula Park (3 min walk)', ARRAY['gym', 'concierge', 'riverside_terrace', 'bike_storage', 'communal_gardens'], ARRAY['/placeholder.svg'], '[{"station": "North Greenwich", "line": "Jubilee", "walk_time": 6}]'),

-- Countryside Developments
('countryside-acton-gardens', 'Acton Gardens', 'Countryside', 'Acton, W3', 'W3 8JT', 51.5103, -0.2691, 'South Acton', 'Overground', '5 min', 'Zone 3', '{"studio": 355000, "1bed": 440000, "2bed": 580000, "3bed": 715000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Acton Gardens is transforming South Acton with new parks, homes, and community facilities. Excellent connections to Ealing Broadway and central London.', '7/10', 'Acton Park (on-site)', ARRAY['gym', 'concierge', 'park', 'community_centre', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "South Acton", "line": "Overground", "walk_time": 5}]'),

('countryside-queensbury', 'The Green Quarter', 'Countryside', 'Queensbury, NW9', 'NW9 8UR', 51.5941, -0.2870, 'Queensbury', 'Jubilee', '7 min', 'Zone 4', '{"studio": 310000, "1bed": 385000, "2bed": 505000, "3bed": 625000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'The Green Quarter offers family-friendly living in Queensbury with excellent Jubilee line connections and access to green spaces.', '8/10', 'Fryent Country Park (10 min walk)', ARRAY['gym', 'concierge', 'green_spaces', 'play_areas', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Queensbury", "line": "Jubilee", "walk_time": 7}]'),

-- Canary Wharf Group Developments
('cwg-wood-wharf', 'Wood Wharf', 'Canary Wharf Group', 'Canary Wharf, E14', 'E14 9SG', 51.5020, -0.0195, 'Canary Wharf', 'Jubilee, Elizabeth line, DLR', '5 min', 'Zone 2', '{"studio": 495000, "1bed": 625000, "2bed": 875000, "3bed": 1250000}', 'Leasehold', 'Q3 2026', ARRAY[0,1,2,3], 'Available', 'Wood Wharf is the new residential district of Canary Wharf offering waterside living with unrivalled transport connections and access to world-class amenities.', '10/10', 'Crossharbour Park (5 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'concierge', '24hr_security', 'cinema_room', 'residents_lounge', 'waterside_terraces', 'shopping', 'restaurants'], ARRAY['/placeholder.svg'], '[{"station": "Canary Wharf", "line": "Jubilee, Elizabeth line, DLR", "walk_time": 5}]'),

('cwg-south-quay-plaza', 'South Quay Plaza', 'Canary Wharf Group', 'South Quay, E14', 'E14 9SH', 51.4998, -0.0198, 'South Quay', 'DLR', '2 min', 'Zone 2', '{"studio": 475000, "1bed": 600000, "2bed": 835000, "3bed": 1185000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'South Quay Plaza is an iconic twin-tower development offering luxury living in Canary Wharf with stunning views across London.', '10/10', 'South Dock Marina (2 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'concierge', '24hr_security', 'sky_gardens', 'residents_lounge', 'waterside_views'], ARRAY['/placeholder.svg'], '[{"station": "South Quay", "line": "DLR", "walk_time": 2}, {"station": "Canary Wharf", "line": "Jubilee, Elizabeth line", "walk_time": 8}]'),

-- Hill Developments
('hill-brentford-locks', 'Brentford Lock', 'Hill', 'Brentford, TW8', 'TW8 8EY', 51.4881, -0.2964, 'Brentford', 'South Western Railway', '8 min', 'Zone 3', '{"studio": 350000, "1bed": 435000, "2bed": 575000, "3bed": 710000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Brentford Lock is a canalside development offering waterside living with easy access to Kew Gardens, Richmond, and Central London.', '7/10', 'Grand Union Canal walks', ARRAY['gym', 'concierge', 'canalside_terrace', 'bike_storage', 'waterside_walks'], ARRAY['/placeholder.svg'], '[{"station": "Brentford", "line": "South Western Railway", "walk_time": 8}]'),

('hill-commerce-road', 'Commerce Road', 'Hill', 'Brentford, TW8', 'TW8 8GA', 51.4872, -0.3047, 'Brentford', 'South Western Railway', '10 min', 'Zone 3', '{"studio": 345000, "1bed": 430000, "2bed": 565000, "3bed": 700000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Commerce Road continues Hill''s transformation of Brentford, offering contemporary homes close to Kew Gardens and excellent rail connections.', '7/10', 'Syon Park (15 min walk)', ARRAY['gym', 'concierge', 'communal_gardens', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Brentford", "line": "South Western Railway", "walk_time": 10}]'),

('hill-brentford-high-street', 'High Street Quarter', 'Hill', 'Brentford, TW8', 'TW8 8BH', 51.4858, -0.3018, 'Brentford', 'South Western Railway', '6 min', 'Zone 3', '{"studio": 355000, "1bed": 440000, "2bed": 580000, "3bed": 720000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'High Street Quarter is at the heart of Brentford''s regeneration, offering modern living with shops, cafes, and restaurants on your doorstep.', '7/10', 'Boston Manor Park (10 min walk)', ARRAY['gym', 'concierge', 'shops', 'cafes', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Brentford", "line": "South Western Railway", "walk_time": 6}]'),

('hill-wandsworth', 'The Ram Quarter', 'Hill', 'Wandsworth, SW18', 'SW18 1SZ', 51.4574, -0.1906, 'Wandsworth Town', 'South Western Railway', '5 min', 'Zone 2-3', '{"studio": 395000, "1bed": 490000, "2bed": 645000, "3bed": 800000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'The Ram Quarter transforms the historic Young''s Brewery site into a new residential quarter in Wandsworth with excellent rail connections to Waterloo.', '8/10', 'Wandsworth Common (10 min walk)', ARRAY['gym', 'concierge', 'heritage_courtyard', 'restaurants', 'shops', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Wandsworth Town", "line": "South Western Railway", "walk_time": 5}]'),

-- Lendlease Developments
('lendlease-elephant-park', 'Elephant Park', 'Lendlease', 'Elephant & Castle, SE17', 'SE17 1FQ', 51.4949, -0.0998, 'Elephant & Castle', 'Northern, Bakerloo', '5 min', 'Zone 1-2', '{"studio": 425000, "1bed": 535000, "2bed": 710000, "3bed": 895000}', 'Leasehold', 'Q3 2026', ARRAY[0,1,2,3], 'Available', 'Elephant Park is London''s largest regeneration creating a new 7-acre park and homes in the heart of Elephant & Castle with excellent transport links.', '9/10', 'Elephant Park (on-site)', ARRAY['gym', 'concierge', 'park', 'cinema', 'restaurants', 'shops', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Elephant & Castle", "line": "Northern, Bakerloo", "walk_time": 5}]'),

('lendlease-trafalgar-place', 'Trafalgar Place', 'Lendlease', 'Elephant & Castle, SE17', 'SE17 1JL', 51.4939, -0.0985, 'Elephant & Castle', 'Northern, Bakerloo', '6 min', 'Zone 1-2', '{"studio": 415000, "1bed": 525000, "2bed": 695000, "3bed": 875000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'Trafalgar Place is part of the Elephant & Castle regeneration offering modern homes with park views and excellent connectivity.', '9/10', 'Elephant Park (adjacent)', ARRAY['gym', 'concierge', 'park_views', 'bike_storage', 'communal_terrace'], ARRAY['/placeholder.svg'], '[{"station": "Elephant & Castle", "line": "Northern, Bakerloo", "walk_time": 6}]'),

-- London Square Developments
('londonsq-bermondsey', 'London Square Bermondsey', 'London Square', 'Bermondsey, SE1', 'SE1 5JE', 51.4967, -0.0719, 'Bermondsey', 'Jubilee', '8 min', 'Zone 2', '{"studio": 420000, "1bed": 530000, "2bed": 700000, "3bed": 880000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'London Square Bermondsey offers contemporary living in vibrant Bermondsey with easy access to London Bridge and the City.', '9/10', 'Bermondsey Spa Gardens (5 min walk)', ARRAY['gym', 'concierge', 'rooftop_terrace', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Bermondsey", "line": "Jubilee", "walk_time": 8}]'),

('londonsq-canada-water', 'London Square Canada Water', 'London Square', 'Canada Water, SE16', 'SE16 7QD', 51.4977, -0.0493, 'Canada Water', 'Jubilee, Overground', '5 min', 'Zone 2', '{"studio": 405000, "1bed": 510000, "2bed": 675000, "3bed": 845000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'London Square Canada Water is part of a major regeneration offering waterside living with excellent Jubilee line connections.', '9/10', 'Russia Dock Woodland (5 min walk)', ARRAY['gym', 'concierge', 'waterside_location', 'bike_storage', 'communal_gardens'], ARRAY['/placeholder.svg'], '[{"station": "Canada Water", "line": "Jubilee, Overground", "walk_time": 5}]'),

('londonsq-caledonian', 'London Square Caledonian Road', 'London Square', 'Islington, N7', 'N7 9AG', 51.5495, -0.1185, 'Caledonian Road', 'Piccadilly', '5 min', 'Zone 2', '{"studio": 440000, "1bed": 555000, "2bed": 735000, "3bed": 925000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'London Square Caledonian Road offers stylish apartments in Islington with Piccadilly line access and proximity to King''s Cross.', '9/10', 'Copenhagen Fields (8 min walk)', ARRAY['gym', 'concierge', 'rooftop_terrace', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Caledonian Road", "line": "Piccadilly", "walk_time": 5}]'),

('londonsq-spitalfields', 'London Square Spitalfields', 'London Square', 'Spitalfields, E1', 'E1 5LJ', 51.5190, -0.0753, 'Liverpool Street', 'Central, Metropolitan, Circle, Elizabeth line', '8 min', 'Zone 1', '{"studio": 525000, "1bed": 665000, "2bed": 935000, "3bed": 1325000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'London Square Spitalfields offers luxury Zone 1 living in the heart of East London with unrivalled transport connectivity.', '10/10', 'Altab Ali Park (5 min walk)', ARRAY['gym', 'concierge', '24hr_security', 'rooftop_terrace', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Liverpool Street", "line": "Central, Metropolitan, Circle, Elizabeth line", "walk_time": 8}]'),

-- Mount Anvil Developments  
('mountanvil-one-clapham', 'One Clapham', 'Mount Anvil', 'Clapham, SW4', 'SW4 0JQ', 51.4634, -0.1396, 'Clapham High Street', 'Overground', '3 min', 'Zone 2', '{"studio": 425000, "1bed": 535000, "2bed": 710000, "3bed": 895000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'One Clapham brings contemporary living to vibrant Clapham with easy access to Clapham Common and excellent transport links.', '8/10', 'Clapham Common (8 min walk)', ARRAY['gym', 'concierge', 'rooftop_terrace', 'bike_storage', 'residents_lounge'], ARRAY['/placeholder.svg'], '[{"station": "Clapham High Street", "line": "Overground", "walk_time": 3}]'),

('mountanvil-queens-cross', 'Queens Cross', 'Mount Anvil', 'Kings Cross, N1', 'N1C 4BN', 51.5369, -0.1234, 'Kings Cross St Pancras', 'Northern, Piccadilly, Victoria, Circle, Metropolitan, Hammersmith & City, Elizabeth line', '8 min', 'Zone 1', '{"studio": 525000, "1bed": 665000, "2bed": 935000, "3bed": 1325000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Queens Cross offers luxury apartments in the heart of the Kings Cross regeneration with unparalleled connectivity across London and beyond.', '10/10', 'Camley Street Natural Park (5 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'concierge', '24hr_security', 'cinema_room', 'business_lounge', 'rooftop_terrace', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Kings Cross St Pancras", "line": "Northern, Piccadilly, Victoria, Circle, Metropolitan, Hammersmith & City, Elizabeth line", "walk_time": 8}]'),

('mountanvil-millbrook-park', 'Millbrook Park', 'Mount Anvil', 'Mill Hill, NW7', 'NW7 1RF', 51.6172, -0.2357, 'Mill Hill Broadway', 'Thameslink', '8 min', 'Zone 4', '{"studio": 320000, "1bed": 400000, "2bed": 525000, "3bed": 650000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'Millbrook Park is a green neighbourhood in Mill Hill offering family homes with excellent schools and Thameslink connections to Central London.', '7/10', 'Millbrook Park (on-site)', ARRAY['gym', 'park', 'play_areas', 'community_centre', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Mill Hill Broadway", "line": "Thameslink", "walk_time": 8}]'),

-- Regal London Developments
('regal-princes-riverside', 'Prince''s Riverside', 'Regal London', 'Rotherhithe, SE16', 'SE16 5HW', 51.5011, -0.0581, 'Canada Water', 'Jubilee, Overground', '12 min', 'Zone 2', '{"studio": 395000, "1bed": 500000, "2bed": 660000, "3bed": 830000}', 'Leasehold', 'Q1 2026', ARRAY[0,1,2,3], 'Available', 'Prince''s Riverside offers Thames-side living in Rotherhithe with views across to Canary Wharf and excellent transport connections.', '8/10', 'Russia Dock Woodland (10 min walk)', ARRAY['gym', 'concierge', 'riverside_terrace', 'bike_storage', 'river_views'], ARRAY['/placeholder.svg'], '[{"station": "Canada Water", "line": "Jubilee, Overground", "walk_time": 12}]'),

('regal-one-blackfriars', 'One Blackfriars', 'Regal London', 'Southwark, SE1', 'SE1 9DG', 51.5062, -0.1043, 'Southwark', 'Jubilee', '5 min', 'Zone 1', '{"studio": 585000, "1bed": 745000, "2bed": 1050000, "3bed": 1485000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'One Blackfriars is an iconic tower offering luxury apartments with stunning views across London. Prime Zone 1 location with excellent transport links.', '10/10', 'Bernie Spain Gardens (5 min walk)', ARRAY['gym', 'swimming_pool', 'spa', 'concierge', '24hr_security', 'sky_lounge', 'cinema_room', 'valet_parking', 'panoramic_views'], ARRAY['/placeholder.svg'], '[{"station": "Southwark", "line": "Jubilee", "walk_time": 5}, {"station": "Blackfriars", "line": "Circle, District", "walk_time": 8}]'),

-- Taylor Wimpey Central London Developments
('taylorwimpey-arsenal-riverside', 'Arsenal Riverside', 'Taylor Wimpey Central London', 'Highbury, N5', 'N5 1LP', 51.5545, -0.1047, 'Arsenal', 'Piccadilly', '8 min', 'Zone 2', '{"studio": 425000, "1bed": 535000, "2bed": 710000, "3bed": 895000}', 'Leasehold', 'Q2 2026', ARRAY[0,1,2,3], 'Available', 'Arsenal Riverside is a new neighbourhood beside Finsbury Park offering contemporary homes with excellent Piccadilly line connections.', '8/10', 'Finsbury Park (10 min walk)', ARRAY['gym', 'concierge', 'riverside_walks', 'bike_storage', 'communal_gardens'], ARRAY['/placeholder.svg'], '[{"station": "Arsenal", "line": "Piccadilly", "walk_time": 8}]'),

('taylorwimpey-battersea-reach', 'Battersea Reach', 'Taylor Wimpey Central London', 'Battersea, SW18', 'SW18 1UQ', 51.4677, -0.1978, 'Wandsworth Town', 'South Western Railway', '12 min', 'Zone 2-3', '{"studio": 410000, "1bed": 515000, "2bed": 680000, "3bed": 855000}', 'Leasehold', 'Completed', ARRAY[0,1,2,3], 'Available', 'Battersea Reach is a riverside community offering Thames-side living with views, riverside walks, and excellent connectivity.', '8/10', 'Thames riverside walks', ARRAY['gym', 'concierge', 'riverside_walks', 'bike_storage', 'river_views', 'marina'], ARRAY['/placeholder.svg'], '[{"station": "Wandsworth Town", "line": "South Western Railway", "walk_time": 12}]'),

('taylorwimpey-phoenix-court', 'Phoenix Court', 'Taylor Wimpey Central London', 'Vauxhall, SW8', 'SW8 2PF', 51.4862, -0.1234, 'Vauxhall', 'Victoria', '6 min', 'Zone 1-2', '{"studio": 435000, "1bed": 550000, "2bed": 725000, "3bed": 915000}', 'Leasehold', 'Q3 2025', ARRAY[0,1,2,3], 'Available', 'Phoenix Court offers modern living in Vauxhall with excellent Victoria line connections and proximity to the Thames.', '9/10', 'Vauxhall Park (8 min walk)', ARRAY['gym', 'concierge', 'rooftop_terrace', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Vauxhall", "line": "Victoria", "walk_time": 6}]'),

('taylorwimpey-trinity-square', 'Trinity Square', 'Taylor Wimpey Central London', 'Hounslow, TW3', 'TW3 1EE', 51.4679, -0.3657, 'Hounslow Central', 'Piccadilly', '5 min', 'Zone 4', '{"studio": 295000, "1bed": 365000, "2bed": 480000, "3bed": 595000}', 'Leasehold', 'Q4 2025', ARRAY[0,1,2,3], 'Available', 'Trinity Square brings contemporary homes to Hounslow with excellent Piccadilly line access to Heathrow and Central London.', '8/10', 'Lampton Park (8 min walk)', ARRAY['gym', 'concierge', 'communal_gardens', 'bike_storage'], ARRAY['/placeholder.svg'], '[{"station": "Hounslow Central", "line": "Piccadilly", "walk_time": 5}]')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  developer = EXCLUDED.developer,
  location = EXCLUDED.location,
  postcode = EXCLUDED.postcode,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  nearest_tube = EXCLUDED.nearest_tube,
  nearest_tube_line = EXCLUDED.nearest_tube_line,
  distance_to_tube = EXCLUDED.distance_to_tube,
  zone = EXCLUDED.zone,
  prices = EXCLUDED.prices,
  tenure = EXCLUDED.tenure,
  completion_date = EXCLUDED.completion_date,
  bedrooms = EXCLUDED.bedrooms,
  status = EXCLUDED.status,
  area_overview = EXCLUDED.area_overview,
  transport_score = EXCLUDED.transport_score,
  green_spaces = EXCLUDED.green_spaces,
  amenities = EXCLUDED.amenities,
  images = EXCLUDED.images,
  stations = EXCLUDED.stations,
  updated_at = now();